### ISSUE TITLE
Adding the signature value to the xml signature.

### ISSUE THREAD

**Issue by Thedakap** [universitatjaumei/jxades#2]
Is it possible to calculate the signature value (Encrypt(hash(signatureInfo))) externally and just add it to the signature. For example i want to calculate the signature value using a javacard, it has a private key that i do not want to expose to the outside world (out of the card), so i want to send the digest of the signedInfo to the card and it should return the encrypted digest....then i want to add this response as the signature value to the xml file. Thank you in advance.

**Comment by borillo** [comment]
Hi @Thedakap,

As long as we know, using the JSR-105 API provided with JDK, there is no way to provide the SignatureValue externally in a direct and well defined way.

Anyway, our collaboration with the "Cliente de @firma" project drives us to a very hacky but effective way to do this.

In this project we have implemented a 3 phase (proxy) signature service for XAdES in order to provide an initial structure of a signed document, then compute the SignatureValue remotely in an applet and finally complete the final document with all the mandatory cryptographic info.

In order to checkout the code you have to register first here:
http://forja-ctt.administracionelectronica.gob.es/web/lang/en/proyectos/clienteafirma

And then connect to:
http://svn-ctt.administracionelectronica.gob.es/svn/clienteafirma/projects/cliente-afirma/trunk/afirma-server-triphase-signer/src/main/java/es/gob/afirma/triphase/server/

Hope it helps :)

**Comment by Thedakap** [comment]
Thank you for the quick response and the links. I am on it and will close the issue if it will do it for me ☺️.
